# Generated by Django 2.1.2 on 2018-10-17 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sccontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('file1', models.CharField(max_length=50, null=True)),
                ('file2', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='scover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('file1', models.CharField(max_length=50, null=True)),
                ('file2', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='simages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('file1', models.CharField(max_length=50, null=True)),
                ('file2', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('time', models.DateTimeField(max_length=20)),
                ('good', models.IntegerField()),
                ('view', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('file1', models.CharField(max_length=100, null=True)),
                ('file2', models.CharField(max_length=100, null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.condition')),
            ],
        ),
        migrations.AddField(
            model_name='simages',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.strategy'),
        ),
        migrations.AddField(
            model_name='scover',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.strategy'),
        ),
        migrations.AddField(
            model_name='sccontent',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.strategy'),
        ),
    ]
