# Generated by Django 2.1.2 on 2018-10-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_auto_20181018_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sccontent',
            name='contents',
            field=models.TextField(default='还没有攻略信息'),
        ),
    ]
