# Generated by Django 2.1.2 on 2018-10-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_auto_20181018_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sccontent',
            name='contents',
            field=models.TextField(default='not have message'),
        ),
    ]
