# Generated by Django 2.1.2 on 2018-10-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='content',
            field=models.TextField(),
        ),
    ]
