# Generated by Django 2.1.1 on 2018-10-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_auto_20181018_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='userid',
        ),
    ]
