# Generated by Django 2.1.1 on 2018-10-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_content'),
        ('strategy', '0007_remove_strategy_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
