# Generated by Django 2.1.1 on 2018-10-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_content'),
        ('travelnote', '0002_auto_20181018_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='tcollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelnote.travelnote')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
