# Generated by Django 2.1.2 on 2018-10-21 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelnote', '0003_tcollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelnote',
            name='userid',
        ),
    ]
