# Generated by Django 2.1.2 on 2018-10-21 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_content'),
        ('travelnote', '0004_remove_travelnote_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelnote',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
